In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd
import numpy as np

df = pd.read_csv("/content/drive/MyDrive/visa_estimator_regression.csv")
df.head()

,education_level,experience_years,annual_salary_usd,company_size,age,country_score,job_skill_score,previous_visas,application_score,visa_approval_score
0,4,15,52939,1196,42,0.501252,0.313991,5,0.588091,100.0
1,5,13,80601,5168,39,0.902772,0.994638,1,0.896613,100.0
2,3,9,48101,7874,21,0.925827,0.644535,4,0.925796,100.0
3,5,6,92710,9932,51,0.724348,0.633114,1,0.605607,100.0
4,5,12,41514,4099,54,0.546535,0.734640,4,0.856800,100.0

In [4]:
df.shape
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   education_level      5000 non-null   int64
 1   experience_years     5000 non-null   int64
 2   annual_salary_usd    5000 non-null   int64
 3   company_size         5000 non-null   int64
 4   age                  5000 non-null   int64
 5   country_score        5000 non-null   float64
 6   job_skill_score      5000 non-null   float64
 7   previous_visas       5000 non-null   int64
 8   application_score    5000 non-null   float64
 9   visa_approval_score  5000 non-null   float64
dtypes: float64(4), int64(6)
memory usage: 390.8 KB

,education_level,experience_years,annual_salary_usd,company_size,age,country_score,job_skill_score,previous_visas,application_score,visa_approval_score
count,5000.000000,5000.00000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,3.010800,10.02260,89636.748000,5013.220000,37.492200,0.704602,0.650272,2.473400,0.749701,99.759516
std,1.424601,6.03594,25058.441772,2905.847208,9.667814,0.173588,0.201283,1.692769,0.144363,1.662585
min,1.000000,0.00000,30000.000000,11.000000,21.000000,0.400012,0.300072,0.000000,0.500102,72.419373
25%,2.000000,5.00000,72499.750000,2456.750000,29.000000,0.555065,0.480420,1.000000,0.626474,100.000000
50%,3.000000,10.00000,89443.500000,5097.500000,37.000000,0.708727,0.650283,2.000000,0.748205,100.000000
75%,4.000000,15.00000,106614.500000,7556.500000,46.000000,0.854123,0.824415,4.000000,0.874810,100.000000
max,5.000000,20.00000,178601.000000,9999.000000,54.000000,0.999935,0.999982,5.000000,0.999714,100.000000

In [5]:
df.isnull().sum()

education_level        0
experience_years       0
annual_salary_usd      0
company_size           0
age                    0
country_score          0
job_skill_score        0
previous_visas         0
application_score      0
visa_approval_score    0
dtype: int64

In [6]:
X = df.drop("visa_approval_score", axis=1)
y = df["visa_approval_score"]

In [7]:
X.dtypes
y.dtype

dtype('float64')

In [8]:
clean_path = "/content/drive/MyDrive/visa_estimator_cleaned.csv"
df.to_csv(clean_path, index=False)

clean_path

'/content/drive/MyDrive/visa_estimator_cleaned.csv'